### ISSUE TITLE
Bug in install-tool; Unable to specify tool version

### ISSUE THREAD

**Issue by afiune** [chef/ci-studio-common#56]
## Problem
There’s a bug with some usage of the`install-tool` utility. Right now it supports passing in multiple tools (e.g. `install-tool hab aws`), but this breaks the desired functionality of being able to specify versions (e.g. `install-tool terraform 0.10.x`). 

## Solution
Split single calls (`install-tool hab aws`) into two calls (`install-tool hab` and `install-tool aws`)

**Comment by tduffield** [comment]
Marking this as done.
